### PR TITLE
Add wdl

### PR DESCRIPTION
**Pull request by NatalieEO**

### CODE REVIEW

**Review by agduncan94 — APPROVED** [review]

**Comment by agduncan94** [comment]
Approved but noticed it is failing. Does the CI test that the workflow works?

**Review by denis-yuen — CHANGES_REQUESTED** [review]
No, it tests that the workflow builds. Which is probably worth doing, seems like it could be a simple Java 8 to 11 upgrade.

**Comment by garyluu** [comment]
Ya, this happened in my bwa-mem PR.  Should be fairly simple

**Comment by garyluu** [comment]
I also had the 501 maven issue. See my PR for inspiration: https://github.com/ICGC-TCGA-PanCancer/Seqware-BWA-Workflow/pull/25/files

**Review by denis-yuen — APPROVED** [review]

**Review by garyluu — APPROVED** [review]

**Pull request merged**
